-- MySQL Script generated by MySQL Workbench
-- Thu Sep 28 10:20:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema IFSPStoreDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `IFSPStoreDB` ;

-- -----------------------------------------------------
-- Schema IFSPStoreDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IFSPStoreDB` DEFAULT CHARACTER SET utf8 ;
USE `IFSPStoreDB` ;

-- -----------------------------------------------------
-- Table `IFSPStoreDB`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IFSPStoreDB`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `IFSPStoreDB`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `Senha` VARCHAR(45) NULL,
  `Login` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `DataCadastro` TIMESTAMP NULL,
  `DataLogin` TIMESTAMP NULL,
  `Ativo` BINARY NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IFSPStoreDB`.`Cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IFSPStoreDB`.`Cidade` ;

CREATE TABLE IF NOT EXISTS `IFSPStoreDB`.`Cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `Estado` VARCHAR(2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IFSPStoreDB`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IFSPStoreDB`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `IFSPStoreDB`.`Cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `Endereco` VARCHAR(100) NULL,
  `Documento` VARCHAR(45) NULL,
  `Bairro` VARCHAR(45) NULL,
  `idCidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Cliente_Cidade`
    FOREIGN KEY (`idCidade`)
    REFERENCES `IFSPStoreDB`.`Cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IFSPStoreDB`.`Venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IFSPStoreDB`.`Venda` ;

CREATE TABLE IF NOT EXISTS `IFSPStoreDB`.`Venda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Data` TIMESTAMP NULL,
  `ValorTotal` DECIMAL(10,2) NULL,
  `idUsuario` INT NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Venda_Usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `IFSPStoreDB`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `IFSPStoreDB`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IFSPStoreDB`.`Grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IFSPStoreDB`.`Grupo` ;

CREATE TABLE IF NOT EXISTS `IFSPStoreDB`.`Grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IFSPStoreDB`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IFSPStoreDB`.`Produto` ;

CREATE TABLE IF NOT EXISTS `IFSPStoreDB`.`Produto` (
  `id` INT NOT NULL,
  `Nome` VARCHAR(100) NULL,
  `Preco` DECIMAL(10,2) NULL,
  `Quantidade` INT NULL,
  `DataCompra` DATE NULL,
  `UnidadeVenda` VARCHAR(10) NULL,
  `idGrupo` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Produto_Grupo`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `IFSPStoreDB`.`Grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IFSPStoreDB`.`VendaItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IFSPStoreDB`.`VendaItem` ;

CREATE TABLE IF NOT EXISTS `IFSPStoreDB`.`VendaItem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Quantidade` INT NULL,
  `ValorUnitario` DECIMAL(10,2) NULL,
  `ValorTotal` DECIMAL(10,2) NULL,
  `idProduto` INT NOT NULL,
  `idVenda` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_VendaItem_Produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `IFSPStoreDB`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VendaItem_Venda1`
    FOREIGN KEY (`idVenda`)
    REFERENCES `IFSPStoreDB`.`Venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
